# Generated by Django 5.2.15 on 2026-06-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('periods', models.JSONField(default=list)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('opinions_found', models.PositiveIntegerField(default=0)),
                ('new_opinions', models.PositiveIntegerField(default=0)),
                ('pdfs_processed', models.PositiveIntegerField(default=0)),
                ('pdf_failures', models.PositiveIntegerField(default=0)),
                ('matches_created', models.PositiveIntegerField(default=0)),
                ('parser_branch', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('anomaly', 'Anomaly'), ('error', 'Error')], default='success', max_length=10)),
                ('error_summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('case_name', models.CharField(blank=True, max_length=500)),
                ('docket', models.CharField(blank=True, max_length=200)),
                ('court', models.CharField(blank=True, max_length=200)),
                ('opinion_type', models.CharField(choices=[('reported', 'Reported'), ('unreported', 'Unreported')], max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-filed_date', '-first_seen_at'],
                'indexes': [models.Index(fields=['opinion_type', 'filed_date'], name='ingestion_o_opinion_a4fd40_idx'), models.Index(fields=['first_seen_at'], name='ingestion_o_first_s_e915a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpinionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='ingestion.opinion')),
            ],
        ),
    ]
