# Generated by Django 5.2.15 on 2026-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_dashboard_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
