# Generated by Django 5.2.15 on 2026-06-11 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('snippets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='keywords.keyword')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ingestion.opinion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matches',
                'indexes': [models.Index(fields=['user', 'created_at'], name='matching_ma_user_id_c61050_idx')],
                'constraints': [models.UniqueConstraint(fields=('opinion', 'user', 'keyword'), name='unique_match')],
            },
        ),
    ]
