# Generated by Django 5.2.15 on 2026-06-11 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('match_whole_word', models.BooleanField(default=True)),
                ('case_insensitive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_keywords', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='keywords.keywordlist')),
            ],
            options={
                'ordering': ['text'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('list__isnull', False), ('owner__isnull', True)), models.Q(('list__isnull', True), ('owner__isnull', False)), _connector='OR'), name='keyword_list_xor_owner'), models.UniqueConstraint(condition=models.Q(('list__isnull', False)), fields=('list', 'text'), name='unique_keyword_per_list'), models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'text'), name='unique_keyword_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='keywords.keywordlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'keyword_list'), name='unique_subscription')],
            },
        ),
    ]
